package dev.rlratcliffe;

import com.datasonnet.document.MediaTypes;
import org.springframework.stereotype.Component;

/**
 * The RoutesImplementation class holds implementations for the end points configured in RoutesGenerated.
 * These routes are based on operation Ids, that correspond to an API end point:  method+path.
 *
 * @author Maven Archetype (camel-openapi-archetype)
 */
@Component
public class RoutesImplementation extends BaseRestRouteBuilder {

    @Override
    public void configure() throws Exception {
        super.configure();
        from(direct("get-hello"))
            .setBody(datasonnet("resource:classpath:test50.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test51.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test52.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test53.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test54.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test55.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test56.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test57.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test58.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test59.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test60.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test61.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test62.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test63.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test64.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test65.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test66.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test67.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test68.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test69.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test70.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test71.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test72.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test73.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test74.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test75.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test76.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test77.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test78.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test79.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test80.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test81.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test82.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test83.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test84.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test85.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test86.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test87.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test88.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test89.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test90.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test91.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test92.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test93.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test94.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test95.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test96.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test97.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test98.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test99.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test100.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("{opId: 'get-hello'}",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
        ;
        from(direct("post-greeting"))
            .setBody(datasonnet("resource:classpath:test2.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test3.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test4.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test5.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test6.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test7.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test8.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test9.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test10.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test10.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test11.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test12.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test13.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test14.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test15.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test16.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test17.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test18.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test19.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test20.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test21.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test22.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test23.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test24.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test25.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test26.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test27.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test28.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test29.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test30.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test31.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test32.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test33.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test34.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test35.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test36.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test37.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test38.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test39.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test40.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test41.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test42.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test43.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test44.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test45.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test46.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test47.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test48.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("resource:classpath:test49.ds",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
            .setBody(datasonnet("{opId: 'post-greeting'}",
                    String.class,
                    MediaTypes.APPLICATION_JSON.toString(),
                    MediaTypes.APPLICATION_JSON.toString())
            )
        ;

    }
}
