name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: '[{ "id": "github-pull", "url": "https://maven.pkg.github.com/ms3inc/camel-rest-extensions" }]'
          servers: '[{ "id": "github-pull", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }]'

      - name: Build 4.4.3-SNAPSHOT of camel datasonnet
        run: |
          mkdir temp
          cd temp
          git clone --depth=400 -b camel-4.4.x https://github.com/apache/camel.git
          cd camel
          git checkout b41ee31adbf6b0bb33b1f328c7d312058b72e5b0
          git --no-pager log -1 --oneline
          mvn clean install --projects :camel-datasonnet --also-make -Psource-jar -DskipTests

      - name: Build and package project
        run: mvn clean install